### ISSUE TITLE
as3js crashes when attempting to import undefined packages

### ISSUE THREAD

**Issue by leaf-node** [Cleod9/as3js#10]
When trying to transpile code that refers to packages such as: 

````
flash.utils.Dictionary
flash.display.Sprite
````

as3js crashes rather than printing an error:

````
/dir/node_modules/as3js/runtime.js:834
            if (this.classMapFiltered[this.packageMap[this.imports[i]].className]) {
                                                                      ^

TypeError: Cannot read property 'className' of undefined
    at AS3Class.toString (/dir/node_modules/as3js/runtime.js:834:71)
    at Main.compile (/dir/node_modules/as3js/runtime.js:306:109)
    at Object.<anonymous> (/dir/node_modules/as3js/bin/as3jsc.js:95:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
````

**Comment by leaf-node** [comment]
For anyone with this issue: you can comment out the includes and remove code and/or use the `--ignore-flash` option.

**Comment by Cleod9** [comment]
Was just about to answer that, yes that's the correct fix!

**Comment by leaf-node** [comment]
Cool, but I see one issue: if one of many source files Depends on arbitrary `DependencyX.Y.Z`, then as3js will crash without printing the name of dependency. As a result, one must grep for all of the import statements for unrecognized modules or packages, or one must search through the as3js code to find the place to put debug statements so one can print the list of missing dependencies.

It would be really helpful if whenever a non-existent package is imported that the name of the first detected missing package is printed.

**Comment by Cleod9** [comment]
@sudoman 

Added a warning message for missing class paths in 0.3.1 :)

https://github.com/Cleod9/as3js/commit/104638c7ebf7b9763590e040e60c77940724000a#diff-180a4c8e5bf3b0c453ab1a7e06c9e0ceR829

**Comment by leaf-node** [comment]
thanks! : D
