### ISSUE TITLE
Do class member references need to be prefixed by their class name?

### ISSUE THREAD

**Issue by leaf-node** [Cleod9/as3js#11]
I'm not sure if this is supposed to work in AS3, but while porting some code, I've seen a few examples like this:

https://gitlab.com/sudoman/box2dflash2js/commit/890a6f1e4148636937fbdf4fa323bb040030ee85

Which gives the following error:

````
ReferenceError: MakeClipPointVector is not defined
````

````
    };Program["Box2D.Collision.b2Collision"]=function(module, exports){  var ClipVertex, b2Manifold, b2Vec2, b2Settings;
    module.inject = function () {
...
      b2Collision.s_incidentEdge = MakeClipPointVector();
````

I've only seen a few examples so far, so perhaps it is bad form for which AS3 compilers are more forgiving.

Is this something that should be handled automatically?

**Comment by Cleod9** [comment]
Interesting, I could have sworn I handled that case in particular. I can take a look and get back to you in day or so. I may have missed an edge case.

**Comment by leaf-node** [comment]
Thanks a bunch! No rush. : )

**Comment by Cleod9** [comment]
Will be addressed with https://github.com/Cleod9/as3js/pull/15

**Comment by Cleod9** [comment]
Merged
