### ISSUE TITLE
Automatically replace "new Dictionary()" with "new Object()"?

### ISSUE THREAD

**Issue by leaf-node** [Cleod9/as3js#12]
It seems like other projects have had success replacing one with the other:

https://github.com/HBehrens/box2d.js/blob/master/convert.py#L107

**Comment by Cleod9** [comment]
Seems simple enough, I should be able to implement this fairly quickly

**Comment by Cleod9** [comment]
Will be addressed with https://github.com/Cleod9/as3js/pull/15

**Comment by Cleod9** [comment]
Merged
