### ISSUE TITLE
Function doesn't transpile corecly

### ISSUE THREAD

**Issue by veso266** [Cleod9/as3js#17]
Hi I would like to translate the folowing AS3 Function into Javascript

AS3 Funtion is here: http://downloads.dxing.si/AS2JS/function.as.txt (if you open it in notepad++ and set Format to ANSI it will display coretly (in browser it has weird characters that are displayed as $ in ANSI)

and it translates to this: https://jsfiddle.net/www6aLfL (when I try to run it I got SyntaxError: illegal character at line 69 (which is this: addr1594: (does this exist in js?))

and I got couple errors when converting from AS3 to JS

`Analyzing class path: §_-7Y§`
`Warning, could not find directory: .\testJS\§_-67§\_`
`Parsing package: _._`
`Warning, missing class path: flash.utils.ByteArray (found in _._)`
`Warning, missing class path: super (found in _._)`
`Warning, missing class path: flash.utils.ByteArray (found in _._)`
`Warning, missing class path: super (found in _._)`
`Done.`
 
Thanks for Anwsering and Best Regards

**Comment by Cleod9** [comment]
Officially closing this project as of today, but I can at least say that AS3JS only supports a limited set of characters. (Variables basically need to match `/[a-zA-Z_$][0-9a-zA-Z_$]*/g` as specified in AS3Pattern.as). Unfortunately there is nothing I can do at this point

Good luck with your project!
