### ISSUE TITLE
No such file or directory"

### ISSUE THREAD

**Issue by crawfordcomeaux** [Cleod9/as3js#2]
Unsure if these warnings are related. I tried installing as3js both globally and locally.

Output from installing locally: 

```
npm WARN unmet dependency /home/crawford/node_modules/lev/node_modules/rc requires minimist@'~0.0.7' but will load
npm WARN unmet dependency /home/crawford/node_modules/lev/node_modules/minimist,
npm WARN unmet dependency which is version 1.1.1
```

Globally:

```
npm WARN unmet dependency /usr/lib/node_modules/meteorite/node_modules/prompt/node_modules/winston requires colors@'0.x.x' but will load
npm WARN unmet dependency /usr/lib/node_modules/meteorite/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
```

**Comment by Cleod9** [comment]
Wow so that's odd... as3js doesn't actually have any third-party dependencies at the moment, so I'm not sure why those warnings would show up. Does this completely prevent as3js from running for you?

I recommend trying the following:

1) Uninstall as3js globally and locally
`npm uninstall -g as3js`
`rm -rf node_modules/` (<-from wherever you have installed locally)

2) Clean up npm cache:
`npm cache clean`

3) Update npm:
`npm update npm -g`

4) Re-install as3js
`npm install as3js` or `npm install -g as3js`

**Comment by crawfordcomeaux** [comment]
Followed all steps; no dice. And it does completely prevent running (responds the same for all options).

I guess the warnings were for unrelated packages installed. 

I'm new to Node, so not sure how to go about debugging this. Any suggestions?

**Comment by Cleod9** [comment]
Oh ok, maybe there is something going on with your local installation of node. Could you let me know a few more details? I'd like to know:
- The method you used to install node (homebrew, official installer, self-built, zipped binaries etc)
- The version of node and npm you are using (that's `npm -v` and `node -v`)
- What OS and OS version you are using

I should note that typically with Node.js, it's just something you install onto your system once and you don't have to think about it again for quite some time. But this sounds like it could be related to how it was installed (such as installing with VS without `sudo` for example)

**Comment by crawfordcomeaux** [comment]
I think you're right. I don't know how I originally installed node, but I think I did something screwy because I've had to use sudo to globally install. I haven't been the best maintainer of my laptop and should probably start over with a more intentional env. I may have installed from the chris-lea PPA initially, which I've since switched over to whatever the official one is now. 

node: v0.12.4
npm: 2.11.2
OS: Ubuntu 14.04

**Comment by Cleod9** [comment]
Ahh ok, so maybe that is it then. I've always built from source for Node on Ubuntu, but it takes forever so I don't necessarily recommend that.

I was able to get it working on my Ubuntu machine just now using the PPA mentioned in this article here:

https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server

Though I did have issues installing as3js  it as a global script with the `-g` flag ("No such file or directory" error). I'll investigate why that happens, but this shouldn't prevent you from installing without the global flag.

Let me know if that helps!

**Comment by Cleod9** [comment]
Hey @crawfordcomeaux, so you can disregard everything I had said about using the other PPA. If you successfully installed via the official repos, it should definitely work now as either a global or local script. I've pushed up an update 0.1.7 that takes care of the "No such file" issue I was talking about as well.

**Comment by crawfordcomeaux** [comment]
Works perfectly now. Thanks! I hope to open up more issues (and hopefully contribute to the code) as I try to port this decompiled as3 framework.

Closing thanks to 3220179b203bb177950b716ccb4af0fd1ee9e34b

**Comment by Cleod9** [comment]
Glad I could help! Definitely looking forward to more feedback
