### ISSUE TITLE
Investigate Implementing AS3 AST Parser

### ISSUE THREAD

**Issue by Cleod9** [Cleod9/as3js#3]
Creating this thread to track any of my findings on the potential of using an AS3 AST parser in place of my custom Regex parser. AST support isn't my top priority since the coverage from my syntax parser is high enough for me to ship code with it, but I think it would be extremely valuable to have a true parser.

My main motivation behind this is that I uncovered this code in an AS3->TypeScript library that seemed to have originated from a file Adobe wrote:
https://github.com/fdecampredon/as3-to-typescript/blob/master/lib/parser.js

I haven't been able to find the origin of this (it may be a port from Java or some other language?) but I'll list any updates here.

If anyone else happens to stumble upon this and wants to help as well, feel free to join in!

**Comment by crawfordcomeaux** [comment]
I actually gave as3-to-typescript a shot with the hopes of then porting TypeScript to js, but since I'm only working with a specific portion of a large codebase, it seemed like overkill. 

A reusable solution compared to my manual port would be great, though, and probably make it easier to add support for things, since the parser (presumably) already gives complete coverage. 

It seems like the majority of the work would simply be rewriting https://github.com/fdecampredon/as3-to-typescript/blob/master/lib/emitter.js for Javascript rather than TypeScript.

**Comment by Cleod9** [comment]
Oh cool, so if that parser presumably has complete coverage, then everything necessary for a raw JS target should be possible with that emitter.js file. I would need to map those structures to mine. If I find some time I'll mess around with that library a bit and see what happens.

In a way, AS3 is more of a structure for a language than a language itself, so if I can just get the right mapping it just becomes a matter of stripping out the stuff that isn't syntactically correct in JS (it's at least how I got this far with just regex alone)

**Comment by crawfordcomeaux** [comment]
Seems like there'd need to be some thought put into some aspects of the conversion to cover features in AS3 that don't exist in JS. Along those lines, I bet there's some features in ES6/ES7 that would ease things along (eg. classes). 

BTW: why's the project built in AS3?

**Comment by Cleod9** [comment]
Yeah it'll definitely take some thought, I know what needs to be done for most features but others are going to need a decision to be made about how to handle it (such as automatically binding functions to classes, which is the biggest fundamental difference).

ES6 unfortunately lacks some things that I'd have wanted such as instance variable initialization on classes or being able to run super() on anything other than line 1 in a class constructor. It also contains a lot of features that AS3 just doesn't have like destructuring and generators. Since ES5 and AS3 are the most similar in parity, I didn't want to mix and mingle all of these new concepts. (Not to mention that ES6+ will be yet another compile step until they get fully implemented in all browsers)

Anyway, the project was built in AS3 mainly because it was originally written in 1 massive file of vanilla JS (see the [first commit](https://github.com/Cleod9/as3js/commit/0938eef5f231ae6595dd58c6140be040d0cc77a2#diff-168726dbe96b3ce427e7fedce31bb0bc) for reference). Once the library stabilized I wanted to start organizing everything, and I figured why not just write it in AS3 and close the loop? I love the auto-completion and refactoring features in my IDE (FlashDevelop) and It also makes for pretty good test coverage since the library depends on itself in order to work

**Comment by crawfordcomeaux** [comment]
That makes a lot of sense. So would we first need to port the parser to AS3 and should we write jsas3 to accomplish that? XD

**Comment by Cleod9** [comment]
Ha! that's a good question. Luckily AS3 and JS play well together so I could just use the raw JavaScript as-is just for the purpose of getting something off the ground

**Comment by Cleod9** [comment]
@crawfordcomeaux Unfortunately I have no updates on the AST front yet, though I thought you might be interested to know that I've updated the library to v0.2, where the output is now complete vanilla JavaScript (no more external dependencies). Have a look at `runtime.js` if you want to take a peek:

https://github.com/Cleod9/as3js/blob/2e835f632a939b3a4e48092b33f60286f288a863/runtime.js

**Comment by ghost** [comment]
@crawfordcomeaux The parser used in as3-to-typescript isn't very complete, it's missing \u..., and probably many other things.

**Comment by Cleod9** [comment]
Closing since this project is obsolete
