### ISSUE TITLE
Empty package fails

### ISSUE THREAD

**Issue by cshaa** [Cleod9/as3js#5]
Hi,
Your project is amazing!
I was trying to do something similar (C#→JS translator) but gave up after a few lines of code :D

However, I found a few bugs in the convertor.
One of them, probably very easy to fix, is that it doesn't support packages without any class.

This code:

``` actionscript
package Box2D.Common {
  public namespace b2internal = "http://www.box2d.org/ns/b2internal";
}
```

Fails with: `Error: Error, no class provided for package: Common.b2internal`  
But when I add a dummy class, all works OK.

``` actionscript
package Box2D.Common {
  public namespace b2internal = "http://www.box2d.org/ns/b2internal";
  public class SomeDirtyHack {}
}
```

Thanks for your repo,
m93a

**Comment by Cleod9** [comment]
Oh, sorry I will add to the readme that the `namespace` keyword is not currently supported, and you are expected to provide a class name with each `.as` file. At the moment I don't have any immediate plans to support the namespace keyword since the concept behind it is somewhat foreign to JS. But I think you should be able to work around this by going through your code and replacing namespace usage with regular public/private/protected properties. (AS3JS does not force you to abide by  encapsulation for the time being)

**Comment by Cleod9** [comment]
Oh one more thing, have you heard of DuoCode? If C# is your thing you might want to have a look:

http://duoco.de/

**Comment by cshaa** [comment]
Thanks for the tip!
I've actually found some other project with this purpose, but it seems that DuoCode doesn't mess up the global namespace as it creates only one global object `DuoCode` and doesn't require any libraries other than Vanilla JS.

However, it would be cool to see a website which would be able to convert your code to multiple languages. Eg. it would convert the code into one universal loss-less language\* and then to any other supported language. This would allow sharing base libraries (eg. C++→JS and C#→JS would use the same library for handling types and conversions between them).

*) I'm not willing to create _the ultimate language for coding_, this language would be designed to be easily parsable, not easily used by a human. It would support many, many approaches to do the same thing (eg. events and futures) and would use that one that is more familiar to the target language.

**Comment by Cleod9** [comment]
It would be amazing to have such seamless conversion between languages, but it sounds like a pretty daunting task. But what's interesting is that we're already seeing more and more transpilers to JS for many languages, so in a way JS is like that universal language. Though unfortunately it's not that easy to go back from JS to most of those other more structured languages.

Anyway, I'll be sure to update the readme with the next update. I've just been experimenting with the format of the output code to make it a bit flatter. I want to be able to have a "Try It" editor and at the moment it would be loaded with boilerplate code if I did so.
