### ISSUE TITLE
for(var i:int=0,len:int=arr.lengthi<len;i++)

### ISSUE THREAD

**Issue by as3long** [Cleod9/as3js#8]
AS3: for(var i:int=0,len:int=arr.lengthi<len;i++)

=>

JS:for(var i=0,len:int=arr.lengthi<len;i++)

**Comment by Cleod9** [comment]
Please see the Readme under the Limitations section:

"Typed variable declarations cannot be all on one line"

Sorry about this, it was a bit difficult for me to parse these values with Regex parsing. But at some point hopefully I can resolve some of the limitations.

**Comment by as3long** [comment]
thanks
